services:
  modem-restart:
    image: modem-restart:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MODEM_USERNAME: admin
      MODEM_PASSWORD: yourpassword
      MODEM_IP: 192.168.1.1
      CHECK_INTERVAL_MINUTES: 15
    restart: unless-stopped